### ISSUE TITLE
Would it be necessary to support all the properties in the profile?

### ISSUE THREAD

**Issue by qoo221** [opencomputeproject/HWMgmt-OCP-Profiles#61] opened 2023-12-19 05:25 UTC
Hi sir,

Per my understanding, some properties in the profile cannot be supported, it is also not mandatory in redfish resource spec with specific DUT. Should we consider that it is mandatory to have the properties even though it will need to hardcore with it?

Thank you
Best Regards
Wuling

**Comment by qoo221** [comment] 2023-12-19 09:04
One example is for /redfish/v1/Chassis/1/Power and /redfish/v1/Chassis/1/Thermal, it is suggested to be replaced by other schemas.

**Comment by jcleung5549** [comment] 2023-12-30 21:17
Regarding your first comment, it is unclear how you arrived at your 'understanding' so it is hard to respond to the comment.  Regarding your second comment, I think this is Issue #25, which is a request to support either to old power/thermal model or the new one. Please check the Baseline profile v1.1 (PR #50) to verify whether it resolves this issue for you.

**Comment by jcleung5549** [comment] 2023-12-30 21:20
Based on the comments, this Issue will be labelled a duplicate of #25.  If you have a different issue/example, please file a specific issue.  Thanks.

**Closed** 2024-04-10 19:32 UTC
Labels: Duplicate
